schema_version: 2
corpus:
  name: narwhals
  display_name: Narwhals
  created_at: '2025-12-10T15:40:00Z'
  keywords:
    - narwhals
    - agnostic
    - pandas
    - polars
    - pyarrow
    - dataframe
sources:
  - id: narwhals
    type: git
    repo_url: https://github.com/narwhals-dev/narwhals
    repo_owner: narwhals-dev
    repo_name: narwhals
    branch: main
    docs_root: docs
    last_commit_sha: 71ba9eb79da7f92786cf2f08591d8ce3b4b407fb
    last_indexed_at: '2026-08-31T13:12:46Z'
index:
  format: markdown
  last_updated_at: '2026-07-01T16:14:56Z'
settings:
  include_patterns:
    - '**/*.md'
  exclude_patterns:
    - '**/assets/**'
    - '**/css/**'
    - '**/javascripts/**'
