schema_version: 2
corpus:
  name: ibis
  display_name: Ibis
  created_at: '2025-12-10T15:34:00Z'
  keywords:
  - ibis
  - sql
  - duckdb
  - bigquery
  - postgres
  - portable
  - expression
sources:
- id: ibis
  type: git
  repo_url: https://github.com/ibis-project/ibis
  repo_owner: ibis-project
  repo_name: ibis
  branch: main
  docs_root: docs
  last_commit_sha: 4556dad2c2a9f04468b12237ade271c2e708db4a
  last_indexed_at: '2026-07-01T16:14:56Z'
index:
  format: markdown
  last_updated_at: '2026-07-01T16:14:56Z'
settings:
  include_patterns:
  - '**/*.qmd'
  - '**/*.md'
  exclude_patterns:
  - '**/_freeze/**'
  - '**/posts/**'
  - '**/presentations/**'
